- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Base/BaseUIView.swift
- fairer-iOS/fairer-iOS/Global/Extension/UILabel+Extension.swift
- fairer-iOS/fairer-iOS/Screens/Home/HomeViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeGroupCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/UIComponent/HomeGroupCollectionViewCell.swift
- close #12 
- 피그마에 있는대로 크기를 잡긴했는데, 잡으면서도 찝찝하네요.. 뭔가 좋은 방법이 있다면 알려주세요 !
- 현재 image asset들이 피그마에서 export가 안되는 이슈가 있어서 애플로고로 일단 박아뒀습니다.
- Component를 분리할 때 init과 render같은 함수를 만드는게 번거로워서 BaseUIView를 만들었습니다.
> [ADD] HomeView TitleLabel, CollectionView 추가

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/BackButton.swift
- fairer-iOS/fairer-iOS/Screens/OnboardingProfile/OnboardingProfileViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingProfileImage/SettingProfileImageViewController.swift
- close #45 
|<img src="https://user-images.githubusercontent.com/81340603/202450358-0f7a832c-8994-408e-9abb-4a5083346bb5.png"/>|<img src="https://user-images.githubusercontent.com/81340603/202450379-96480db2-454c-4a9f-a0de-24280bd93693.png" />|
|-|-|
- 하우스 관리 화면 구현
> [ADD] 프로필 사진 설정 뷰 구현

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Screens/ChangeHouseName/ChangeHouseNameViewController.swift
- close #49 
|<img src="https://user-images.githubusercontent.com/81340603/204823388-8a6d8189-2ffe-42ef-9362-e32f4827e617.png" width=150px />|<img src="https://user-images.githubusercontent.com/81340603/204823462-a98c8def-b549-48b8-a5f3-e5681e6a5f0f.png" width=150px />|<img src="https://user-images.githubusercontent.com/81340603/204823536-ff6d8109-beb1-4d89-b480-3dde8114c3a0.png" width=150px />|<img src="https://user-images.githubusercontent.com/81340603/204823621-681342e2-da30-48ec-8fca-d776a4b35ca8.png" width=150px />|
|:---:|:---:|:---:|:---:|
|<center>디폴트</center>|<center>입력값이 없을 때</center>|<center>특수문자</center>|<center>16글자 이상 입력 불가능</center>|
- Title & Secondary Label 추가
- TextField 추가
- 특수문자 금지 로직 추가
- 16글자 이상 입력 못하는 로직 추가
- 키보드 터치하면 버튼이 같이 올라오는 로직 추가
- 입력한 글자가 없을 경우 버튼 비활성화하는 로직 …
> [ADD] 하우스 이름 변경 뷰 구현

- fairer-iOS/fairer-iOS/Screens/HomeViewController.swift
- #68
https://user-images.githubusercontent.com/83629193/216561805-cad9ec0a-d117-4410-8c0c-2dea275717ce.mov
- 스크롤이 시작되는 과정에는 스크롤이 시작되는 부분과 스크롤이 상단에 도착했을 때 모두 애니매이션을 넣었습니다.
- PR을 쪼개서 올리려고 하는 중이라 캘린더 개발, 하단 컬렉션 뷰는 다른 PR에 넣어서 올리도록 할게요!
https://stackoverflow.com/questions/7706152/check-if-a-uiscrollview-reached-the-top-or-bottom
> [FEAT] 스크롤 뷰의 스크롤 이벤트 처리

- fairer-iOS/fairer-iOS/Global/Supports/Info.plist
- fairer-iOS/fairer-iOS/Network/Foundation/BaseTargetType.swift
- close #98
1. http 통신을 위한 설정
2. BaseURL 파일 관련 변수명 수정
- Auth 부분 해결
> [Setting] 네트워크 http 설정 & 수정

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Supports/Info.plist
- close #103 
bundle id 를 수정했습니다.
> [ADD] bundle id 바꾸기

- fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/PickDateView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- close #106 
주간 캘린더와 date picker 날짜 연결.
기존에 date picker와 주간 캘린더 date가 연결되지 않는 부분 해결했습니다.
> [ADD] 주간 캘린더와 date picker 날짜 연결

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- fairer-iOS/fairer-iOS/Global/Supports/AppDelegate.swift
- close #139 
1. firebase spm 추가
2. GoogleService-Info 파일 추가
> [ADD] firebase spm 추가

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/View/InviteCodeButtonView.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/ViewController/HouseInviteCodeViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/ManageHouse/ManageHouseViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
- close #148 
- 설정 > 초대하기 뷰를 구현
- TeamAPI 쪽 이슈가 있어서 준혁님의 "[ADD] 홈뷰 상단 팀 멤버 리스트 중 본인 확인 #149"가 머지가 된 후 테스트가 가능할 것 같습니다!..
- 그룹 > 초대하기 뷰와 거의 동일해서 크게 테스트 할 것은 없을 것 같습니다.
-  애플 로그인
> [ADD] setting - 초대하기 뷰 구현

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Network/API/RulesAPI.swift
- fairer-iOS/fairer-iOS/Network/API/StatisticsAPI.swift
- fairer-iOS/fairer-iOS/Network/Foundation/NetworkService.swift
- fairer-iOS/fairer-iOS/Network/Foundation/URLConstant.swift
- fairer-iOS/fairer-iOS/Network/Router/RulesRouter.swift
- fairer-iOS/fairer-iOS/Network/Router/StatisticsRouter.swift
- close #152 
1. 통계 기능 관련, 코드 파일 삭제
> [CHORE] 통계 기능 관련, 코드 파일 삭제

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Extension/UIApplication+Extension.swift
- fairer-iOS/fairer-iOS/Global/Extension/UIButton+Extension.swift
- fairer-iOS/fairer-iOS/Global/Extension/UINavigationController+Extension.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/BackButton.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/CalendarSpaceView.swift
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingProfile/ViewController/OnboardingProfileViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/ViewController/HouseInfoViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/View/InviteCodeButtonView.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/ViewController/HouseInviteCodeViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseMakeName/HouseMakeNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/ViewController/SelectHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/WriteHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingMain/ViewController/SettingViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingProfileImage/SettingProfileImageViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingProfileViewController.swift
- close #154 
- 앱 전체적인 뷰 네비게이션 연결
- Login 부분 소셜 로그인 처리 없이 푸쉬 버튼 이벤트만 연결해두었습니다.
- SetHouseWorkViewController와 WriteHouseWorkViewController의 init에서 [HouseWorksRequest]를 인자로 받고 있는데 해당 부분에 대한 처리는 빈배열로 해두었습니다.
> [ADD] 뷰 네비게이션 연결

- fairer-iOS/fairer-iOS/Screens/Home/Home/View/HomeGroupView/HomeGroupCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/SettingProfileViewController.swift
- close #166 
- 이미지 재설정 부분 버그 해결
- 홈뷰, 사용자 이름 5글자 일때 ... 되는 버그 해결
> [ADD] SettingProfile ViewController - 사용자 이미지 버그 해결

- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/ViewController/HouseInviteCodeViewController.swift
- close #180 
HouseInViewCodeViewController의 버튼 연결 로직, 중복 해결
> [FIX] AddAction 중복 로직 수정

- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Global/Util/RootHandler.swift
- fairer-iOS/fairer-iOS/Global/Util/UserDefaultHandler.swift
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- close #183 
- isLogin이라는 UserDefault bool값을 추가해서 해당 값을 사용해 SceneDelegate에서 자동로그인 처리 했습니다.
- LoginVC에서 isNewMember을 확인해서 회원가입 유저 분기처리를 했습니다.
- 로그아웃 구현 시 UserDefaultHandler의 모든 값을 nil로 만드는 처리를 하면 될 거 같아요.
-
> [ADD] 자동로그인 및 회원가입 유저 분기처리

- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- close #187 
- 다은님이 이슈 해결 해주셔서 애플 로그인 연동 확인 완료했습니다.
-
> [FEAT] AppleLogin 연동 완료

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Network/API/AlarmAPI.swift
- fairer-iOS/fairer-iOS/Network/DTO/AlarmRequest.swift
- fairer-iOS/fairer-iOS/Network/DTO/AlarmResponse.swift
- fairer-iOS/fairer-iOS/Network/Foundation/NetworkService.swift
- fairer-iOS/fairer-iOS/Network/Router/AlarmRouter.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingAlarm/View/SettingAlarmTableViewCell.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingAlarm/ViewController/SettingAlarmViewController.swift
- 초기 상태: 설정 시간 false, 미완료 리마인드 true
- 설정 시간 true로 변경
- 알람 설정 조회/수정 router/api/dto 생성
- SettingAlarmVC에 api 연결
푸시 알림 기능까지 한 pr에 담으려고 했으나 분량이 커질 것 같아서 쪼갰습니당!
- PushNotification 쪽 개발
- 날짜별 집안일 조회 api 연결
- 미완료 집안일 알림 구현
- 설정 시간 알림 구현
> [ADD] 푸시알림 - api 연결

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Screens/Setting/SettingMain/View/SettingTableViewCell.swift
- close #195 
- 다크모드 막기
- SettingView 이미지 찌그러짐 수정
-
> [FIX] 다크모드 막기, SettingView 이미지 찌그러짐 수정

- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/ViewController/SettingHomeRuleViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/ViewController/View/SettingHomeRuleHeaderView.swift
- close #197 
- 규칙 없을 경우 규칙 라벨 hidden 처리
- 온보딩닉네임뷰 뒤로가기 button 제거
-
> [FIX] 규칙 없을 경우 규칙 라벨 hidden 처리, 뒤로가기 button 삭제

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingInviteCode/SettingInviteCodeViewController.swift
- close #184
- 카카오 공유하기 템플릿 구현
- plist 만들어서 카카오 공유하기 private key 저장
> [ADD] 카카오 공유하기 템플릿 구현

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
- close #218 
- 닉네임 특수문자 금지 핸들링
- 버전 스트링 값 변경
> [FIX] 닉네임 특수문자 금지 핸들링 & 버전 스트링 값 변경

- fairer-iOS/fairer-iOS/Global/Extension/String+Extension.swift
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/EditHouseWork/ViewController/EditHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/View/SelectHouseWorkDetail/SelectHouseWorkDetailCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/ViewController/SelectHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/View/SetHouseWorkCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/ViewController/WriteHouseWorkViewController.swift
- close #207 
[SelectHouseWork 에서 변경한 날짜를 SetHouseWork 에 반영]
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/a6042b51-4c6a-4314-9725-832b16219acb" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/86855aaa-f293-47af-ae28-82692a470932" width=200px />|
|:---:|:---:|
|<center>7월 20일로 변경</center>|<center>반영된 모습</center>|
<br>
[SelectHouseWork 에서 변경한 날짜를 WriteHouseWork 에 반영]
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/a11adc95-0066-4a70-b4ce-d6b085136617" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/d1841d9c-71e7-4406-bd50-0a1e512cc68b" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/91d1e27d-187c-4bb3-a0ab-a9ee122dfcd7" width=200px />| …
> [FIX] Datepicker 데이터 바인딩

- fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/ViewController/SettingHomeRuleViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/ViewController/View/SettingHomeRuleHeaderView.swift
- close #230 
- 간단하게 폰트와 레이아웃 설정을 수정했습니다.
> [FIX] HomeRuleView Label Font 변경 및 레이아웃 조정

- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- close #237 
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/6e6f09f2-6c1e-4614-a065-883ca30957f4" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/80969a16-ac71-4d83-8a26-3b1955c1faed" width=200px />|
|:---:|:---:|
|<center>유저 제외 담당자 선택</center>|<center>들어간 화면</center>|
- 담당자 추가 로직이 잘못되어서 수정했습니다 ~
> [FIX] 내가 아닌 다른 사람을 담당자로 추가했을 때 나까지 들어가는 버그 해결

- fairer-iOS/fairer-iOS/Screens/Home/Home/View/HomeGroupView/HomeGroupCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- close #235 
- 다른 유저 프로필 선택 후 집안일 추가하면 필터링 이슈 해결
- 집안일 모두 했을 때, 주간 캘린더 뱃지 ishidden false 이슈 해결
> [FIX] QA 반영

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
버젼 내용만 수정했습니데이 ~
꿀 피알이죠 ! ㅋㅋㅋ
develop 머지 되면 바로 main 브랜치 업데이트 할게요~
> [CHORE] v1.1.0 릴리즈에 따른 develop 브랜치 업데이트
