fairer-iOS/fairer-iOS

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Screens/SettingAlarm/SettingAlarmViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingAlarm/UIComponent/SettingAlarmTableViewCell.swift
- close #51 
알림을 설정할 수 있는 간단한 뷰를 만들었습니다.
처음에 딱 봤을 때는 동일한 cell들이 list 형태로 정렬되어 있어서 당연히 table view를 사용하여 구현해야 하는 거라고 판단했습니다.
하지만 막상 구현해보니 1) cell의 reuse 의 빈도가 낮고 2) 고정된 list가 스크롤 되고 3) UISwitch가 작동하지 않는 문제들이 발생했습니다.
다시 고민해본 결과, 실현 가능한 해결 방법이 2 개 나왔습니다.
1. 보편적으로 했던 것처럼 cell 컴포넌트를 나열하여 배치한다.
2. StackView 안에서 배치해본다.
현재 PR 은 1번으로 구현되었습니다. 코드가 간단하긴 하지만 중복되는 요소들이 있어서 살짝 아쉬운 감이 있네요.
2번 방법을 사용해보고 이 피알 아래에 코멘트 남기겠습니다.
UIStackView의 정확한 쓰임은?
그냥 autolayout 주면서 배치하는 것과 구체적으로 어떤 게 다른가?
- 문의하기 화면 구현하기
[UITableView를 쓰지 말아야 할 때]
https://soojin.ro/blog/uitableview-hype
[UISwitch resize 하기]
https://www.todaymart.com/336
> [ADD] 알림 설정 뷰 UI 구현

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Extension/UIButton+Extension.swift
- fairer-iOS/fairer-iOS/Global/Literal/SizeLiteral.swift
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Screens/SettingInquiry/SettingInquiryViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingInquiry/UIComponent/SettingInquiryCellView.swift
- close #53 
|<img src="https://user-images.githubusercontent.com/81340603/209565111-c730035c-2ba5-4291-aa91-56bc85bbc8cb.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/209565120-87dc372d-d600-43ec-a10a-697d090c3a63.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/209565114-1828fe48-4ba6-4fff-8182-32ab94d5db57.png" width=200px />|
|:---:|:---:|:---:|
|<center>SettingInquiryView</center>|<center>메일(실패)</center>|<center>인스타그램 연결</center>|
- 파일 & 디렉토리 생성
- navigation bar 생성
- title label 추가
- cell view 생성 및 VC 에 추가
- 인스타그램: safari link 연결
- 메일 앱 연동
- UIView에서 뷰를 띄울 수 없어서(present) UIView에 `didTappedMail`이라는 클로져를 생성한 후 이메일 주소를 눌렀을 때 클로져를 실행하고, 그걸 VC에서 감지하면 mail 앱 뷰를 띄우는 코드를 작성했습니다.
- 현재 핸드폰에서 빌드를 직접 할 수 없는 상황이라서 시뮬레이터로만 테스트를 …
> [ADD] 문의하기 뷰 구현

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Extension/Date+Extension.swift
- fairer-iOS/fairer-iOS/Global/Literal/ImageLiteral.swift
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/repeatcyclechevron.imageset/Contents.json
- fairer-iOS/fairer-iOS/Global/Resource/Assets.xcassets/button/repeatcyclechevron.imageset/repeatcyclechevron.pdf
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/GetManagerView/GetManagerCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/Model/HouseWork.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/RepeatCycle/RepeatCycleCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/RepeatCycle/RepeatCycleCollectionViewCell.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/RepeatCycle/RepeatCycleMenu.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/RepeatCycle/RepeatCycleView.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/SelectManagerCollectionViewCell.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/SelectManagerView.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/SetHouseWorkCalendarView.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/SetHouseWorkCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/UIComponent/SetHouseWorkCollectionViewCell.swift
- close #70 
https://user-images.githubusercontent.com/81340603/216532073-c7011801-5bca-48e4-b638-c7baeeccb314.mp4
- 시간 설정 & 반복하기 Label 과 Switch 생성
- 시간 설정
- DatePicker 생성
- 반복하기
- 반복 주기 설정 (`RepeatCycleView` & `RepeatCycleMenu`)
- 반복 요일 설정(`RepeatCycleCollectionView`)
- 반복 정보 라벨(`RepeatCycleDayLabel`) 생성
- HouseWork Model 생성 및 Mockdata 연결
- 집안일 수정/삭제에 따른 Mockdata 수정/삭제
- 집안일 포커스 변경에 따른 담당자/시간설정/반복하기 업데이트 로직 구현
- 집안일 설정 화면과 관련된 화면 코드 정리
먼저 죄송합니다,,, 사이즈가 너무 큰 피알을 올려버렸네요,,, 나름 크기 줄인다고 3번에 나눠서 구현했는데도
이번 PR에서 UI 외에도 구현해야 할 로직이 너무 많았어요 ㅠㅠㅠ 한 번 시작하니 중간에 멈추면 다시 할 자신도 없어서 일단 다 해버렸습니다,,
1. HouseWork 모델 생성
상단에 있는 집안일 CollectionView에서 어떤 Cell을 터치(포커스)하냐에 따라서 아래 있는 담당자 & 시간 & 반복 컴포넌트가 달라져야 하는 로직을 구현하기 위해 임의로 모델을 만들었습니다. Swagger 를 참고해서 제작했지만 타입이나 변수 이름이 완벽하게 일치하지 않습니다. UI 구현 단계에서 가장 적합한 형식으로 만들어 …
> [ADD] 집안일 설정 완성

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Screens/SetHouseWork/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/WriteHouseWork/WriteHouseWorkViewController.swift
- close #82 
|<img src="https://user-images.githubusercontent.com/81340603/218438978-0c84a3e4-b32e-4d53-9e0d-fcc3ad8144da.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/218438974-deec2d09-b8f9-4a3e-9d7f-6feb2ed614d6.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/218438965-7217e465-db00-4b16-8fea-a2f702239842.png" width=200px />|<img src="https://user-images.githubusercontent.com/81340603/218438950-fea669c8-c846-43a6-8fc6-6103d6565032.png" width=200px />|
|:---:|:---:|:---:|:---:|
|<center>반복 - 매주</center>|<center>반복 - 매달</center>|<center>완료 버튼</center>|<center>스크롤</center>|
- 반복 `Label` & `Toggle` 추가
- `RepeatCycleView`(주기 확인) 추가
- `RepeatCollectionView`(요일 설정) 추가 
- `RepeatCycleMenu`(주기 설정) 추가
- 완료 `Button` 추가
- 유저 액션에 …
> [ADD] 집안일 직접 입력_반복하기 & 마무리

- fairer-iOS/fairer-iOS/Network/API/TeamsAPI.swift
- fairer-iOS/fairer-iOS/Network/Router/TeamsRouter.swift
- fairer-iOS/fairer-iOS/Screens/Setting/ManageHouse/ManageHouseViewController.swift
- close #133 
- postLeaveTeam Router, postLeaveTeam API 추가
- 하우스 나가기 모달에서 나가기 선택 시 post와 동시에 GroupMainView로 push 되도록  구현하였습니다.
- 더불어 push와 함께 기존의 navigation Stack을 모두 제거하고 GroupMainView가 첫번째 navigation Stack이 되도록 하였습니다.
- 팀 나가기를 테스트 하기 전에 팀 초대 API를 통해 참가 코드를 저장해두고, 팀 나가기를 진행해주세요. ( 이후 팀 참가를 위해 )
- GroupMainView에서 navigation Stack이 정상적으로 모두 제거되었는지 확인 하기 위해선 팀 나가기 실행 전 아래 코드를 GroupMainViewController에 추가해주세요.
```
override func viewDidLoad() {
super.viewDidLoad()
if let navigationController = self.navigationController {
for viewController in navigationController.viewControllers {
print("남은 뷰컨은 : \(viewController)")
}
}
}
```
- GroupMainView에 빠진 멤버 이름 get API 연결
https://pooh-footprints.tistory.com/47
> [ADD] teams - 팀 나가기 API 연결

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Network/API/MembersAPI.swift
- fairer-iOS/fairer-iOS/Network/Foundation/NetworkService.swift
- fairer-iOS/fairer-iOS/Network/Router/MembersRouter.swift
- fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
- close #135
- member 정보 조회 API를 생성하고 그룹메인 뷰에 연결했습니다.
didSet이나 DispatchQueue를 사용했을 때 서버 통신이 느린 점에 대한 질문
- 뷰가 만들어짐과 동시에 통신이 이루어져서 정보를 같이 가져 와야 하는데, 뷰가 만들어 진 후 서버 통신이 되어서 뭔가 통신 하는 부분이 한박자 느린 느낌이 듭니다. 공부가 필요하거나 이래서 비동기 프레임워크를 쓰나? 하는 생각이 듭니다. 다른 뷰도 마찬가지 일 거 같아요.
- 멤버 API
> [ADD] members - 내 정보 조회 API 구현 및 그룹 메인 뷰에 바인딩

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Extension/String+Extension.swift
- fairer-iOS/fairer-iOS/Network/API/TeamsAPI.swift
- fairer-iOS/fairer-iOS/Network/DTO/Teams/InviteCodeInfoResponse.swift
- fairer-iOS/fairer-iOS/Network/DTO/Teams/TeamInfoResponse.swift
- fairer-iOS/fairer-iOS/Network/Router/TeamsRouter.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/ViewController/HouseInviteCodeViewController.swift
- close #142 
- 코드 유효 시간 ( 중간 빨간 레이블) 데이터를 파싱하여 바인딩시켰습니다.
- 코드 재발급 버튼 선택 시 팀 초대 API 재실행
- 하우스 이름과 초대코드가 처음에 뜨지 않는 이유는 두 개의 데이터는 push되기 전 뷰인 houseMakeNameVC에서 가져오기 때문에 팀 생성 API를 한번 호출 후 push 될 때 가져오게 됩니다.
- "2023-04-09T19:00:18" 형식으로 코드 만료 기간이 내려와서 해당 형식을 파싱하는 extension을 추가 했습니다.
- 코드 만료 기간과 date를 비교해서 코드 만료기간이 date보다 앞설 시 코드 카카오톡 공유하기 뷰가 else 면 코드 재발급 버튼이 뜨도록 했습니다.
- setting에서의 HouseInviteCodeView
> [ADD] teams - 팀 초대(초대 코드 보기) API 연결

- fairer-iOS/fairer-iOS/Global/UIComponent/LoadingView.swift
- fairer-iOS/fairer-iOS/Network/API/TeamsAPI.swift
- fairer-iOS/fairer-iOS/Network/Router/TeamsRouter.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- close #147
1. 본인 정보 조회 이후 팀 정보 조회하여 본인 아이콘이 상단 팀 리스트에서 가장 왼쪽에 오도록 구현
2. 기본 loading view -> self.view.isUserInteractionEnabled 로 대체
3. 홈뷰 처음 들어갔을 때 의미 없이 뜨던 파란 뱃지 버그 해결
4. 주간 캘린더 가로 스크롤 연속으로 했을 때 발생되던 인덱스 참조 버그 해결
5. 다른 예외 상황 처리에서 Loading View 사용할것 같아 일단 남겨두었어요
- 홈뷰에서 데이터 바인딩 속도가 조금 느린 부분이 있는데 (파란 뱃지), 해당 부분은 좀 더 고민해보려해요!
- 홈뷰는 팀원 이미지 로딩만 해결만 남았고 전체적으로 마무리 되었습니다.
> [ADD] 홈뷰 상단 팀 멤버 리스트 중 본인 확인

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- fairer-iOS/fairer-iOS/Global/Extension/String+Extension.swift
- fairer-iOS/fairer-iOS/Global/Extension/UIImageView+Extension.swift
- fairer-iOS/fairer-iOS/Global/Supports/Info.plist
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/ViewController/HouseInfoViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/ViewController/HouseInviteCodeViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/DailyCollectionView/CalendarDailyTableViewCell.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/HomeGroupView/HomeGroupCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- close #157 
Bug ID | View | Detail | Importance | Finished?
-- | -- | -- | -- | --
1 | LoginVC | 로그인 페이지에서 소셜 로그인 이후 뒤로 돌아가는 백버튼 클릭 시 상단 네비게이션 바 부분 색이 하얀색으로 바뀐다. | p1 | finished!
2 | OnboardingVC | 글자 수가 5개가 되었을 때, 마지막 글자가 완성되지 않는다. | p2 | finished!
3 | UIImage | 전체적으로 이미지 로드 안됨 | p1 | finished!
6 | HomeVC 주간 캘린더 | 주간 캘린더의 터치 이벤트로 ‘월’이 변경 되었을 경우 datepicker 날짜 처리 | p2 | finished!
7 | HomeVC 스크롤 | 홈뷰의 하단 테이블 뷰가 특정 사이즈 이상이 되지 않은 경우, 스크롤 이벤트가 적용되지 않음 | p3 | finished!
8 | HomeVC 규칙 | 규칙 설정 뷰에서 가장 상단의 규칙을 삭제 후 홈뷰로 pop 할 경우 인덱스 참조 에러 남 | p1 | finished!
9 | HomeVC 주간 캘린더 | 다른 뷰로 push 되고 pop 되어 다시 홈뷰로 들어왔을 때, 주간 캘린더 셀 터치로 api 호출 안됨 | p1 | finished!
10 | Navigation | Navigation Controller pop 되었을 때 다음 push가 두번됨 | p1 | finished!
1. 노션 페이지에 iOS, 버그 테이블 작성 이후 위의 1, 2, 3, 6, 7, 8, 9, 10 Bug ID를 …
> [FIX] 버그 테이블 기반 디버깅

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- fairer-iOS/fairer-iOS/Global/Extension/String+Extension.swift
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/Supports/Info.plist
- fairer-iOS/fairer-iOS/Network/API/MembersAPI.swift
- fairer-iOS/fairer-iOS/Network/DTO/MemberPatchRequest.swift
- fairer-iOS/fairer-iOS/Network/DTO/MemberPatchResponse.swift
- fairer-iOS/fairer-iOS/Network/Router/MembersRouter.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingProfile/ViewController/OnboardingProfileViewController.swift
- fairer-iOS/fairer-iOS/Screens/ProfileImageButtonView.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingProfileImage/SettingProfileImageViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingProfileViewController.swift
- close #162 
- Setting ViewController에서 사용자의 이름과 상태 메세지 수정을 구현
- 사용자의 프로필 이미지 수정 구현
- SettingProfileImage 뷰에서 프로필 이미지를 재설정하고 프로필 patch api 호출 이후, SettingProfileImage 뷰가 pop되면 SettingProfileViewController 뷰로 넘어가면 재설정한 프로필의 이미지가 로드되어야 하는데 그 과정에서 api 호출 딜레이로 asyncAfter를 사용하지 않으면 변경 전의 이미지가 로드되는 경우가 있었습니다. 
저는 해당 문제를 asyncAfter로 해결했는데 혹시 다른 더 좋은 방법이 있으면 같이 이야기해보아요!
- Onboarding View 쪽의 프로필 이미지 설정 api 연결
- 회원탈퇴 기능 구현
> [ADD] Setting ViewController - 프로필 재설정, 이미지 재설정 구현

- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingName/OnboardingNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingProfile/ViewController/OnboardingProfileViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
- close #165 
- 소셜 로그인 이후 Onboarding VC에서 사용자 이름과 프로필 받는 부분의 api 연결을 작업했습니다.
- 기존 GroupMainViewController에서 api 호출로 사용자 이름을 받아왔던 부분을 프로퍼티 변수값으로 변경하여 api 호출없이 연결되도록 했습니다.
> [ADD] Onboarding ViewController - 사용자 이름, 프로필 설정 api 연결

- fairer-iOS/fairer-iOS/Global/Util/RootHandler.swift
- fairer-iOS/fairer-iOS/Network/API/HouseWorkCompleteRouterAPI.swift
- fairer-iOS/fairer-iOS/Network/API/MembersAPI.swift
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- close #178 
- 프로비저닝 인증서 설정한 상태에서 다시 애플로그인 구현했습니다.
- credential에서 내려오는 identityToken를 통해 토큰 서드파티로 백엔드와 유효성검사를 진행하면 될 거 같습니다.
- 더불어 최초 로그인에만 이름과 이메일을 받을 수 있고, 두번째 로그인부터는 앱에서 Apple ID 사용 중단하기 전까지 ID 값만 리턴한다고 합니다.
- 가입한 상태에서 앱을 삭제하고 다시 설치 시 로그인 할 때 온보딩이 아닌 메인으로 가게 하려면 어떻게 구현해야하나 고민이 드네요!
- 이전 토큰 풀리퀘에서 발견된 오류가 있어서 이 브랜치 얼른 머지해야 오류 안날 거 같아요!
> [ADD] Apple Login

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/CalendarSpaceView.swift
- fairer-iOS/fairer-iOS/Network/API/HouseWorksAPI.swift
- fairer-iOS/fairer-iOS/Network/DTO/HouseWorks/HouseWorksResponse.swift
- fairer-iOS/fairer-iOS/Network/Router/HouseWorksRouter.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/EditHouseWork/ViewController/EditHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/Model/Space.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/ViewController/SelectHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/ViewController/WriteHouseWorkViewController.swift
- close #182 
|<center>홈: 화장실 청송</center>|<center>수정화면에 반영된 모습</center>|
|:---:|:---:|
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/451f064e-a3af-477e-b93a-6c5ce4fd3e6a" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/83f16556-5f8d-41e3-8698-8cac68191555" width=200px />|
- Home > EditHouseWork: 기존 집안일 바인딩
getHouseWorkById api 연결
홈에서 전달 받은 housework id 를 통해 집안일 정보 콜
컴포넌트에 집안일 정보 반영
집안일 수정/삭제 request 재정리
|<center>공간/세부 집안일 선택</center>|<center>공간/세부 집안일 반영된 모습</center>|
|:---:|:---:|
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/f23e9101-bf0b-4893-bffb-e114b54d1063" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/eff2fbbc-4f15-47d8-b2b1-7251594eed1f" width=200px />|
- …
> [ADD] 집안일 생성/수정 화면 - 데이터 바인딩

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Util/UserDefaultHandler.swift
- fairer-iOS/fairer-iOS/Network/API/FcmAPI.swift
- fairer-iOS/fairer-iOS/Network/DTO/FCMTokenResponse.swift
- fairer-iOS/fairer-iOS/Network/Foundation/NetworkService.swift
- fairer-iOS/fairer-iOS/Network/Router/FCMRouter.swift
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- close #192 
- FCMRouter, FcmAPI에 파일 구현해두었습니다.
- 리스폰스 값으로 fcmToken 값이 넘어오는 거 같아서 해당 값을 저장해두는 userdefaullt 추가해뒀어요
```swift
private func saveFCMToken(token: String) {
NetworkService.shared.fcm.saveToken(token: token) { result in
switch result {
case .success(let response):
guard let data = response as? FCMTokenResponse else { return }
if let fcmToken = data.token {
UserDefaultHandler.fcmToken = fcmToken
}
case .requestErr(let errorResponse):
dump(errorResponse)
guard let data = errorResponse as? UserErrorResponse else { return }
print(data.errorMessage)
default:
print("sign in error")
}
}
}
```
- 요렇게 사용하려고 했어요 유나님!
- 연결 부탁드립니다 감사해요
-
> [ADD] saveToken API 구현

- fairer-iOS/fairer-iOS/Global/Extension/String+Extension.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/GetManagerView/GetManagerCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/View/HouseMemberCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInfo/ViewController/HouseInfoViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/HomeGroupView/HomeGroupCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/EditHouseWork/ViewController/EditHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/ViewController/WriteHouseWorkViewController.swift
- close #194 
- 하우스 멤버를 보여주는 UI 에서 멤버 목록 정렬 로직을 추가했습니다. (유저 > ㄱㄴㄷ순)
- 하우스 멤버의 닉네임을 4글자까지 표시하고 5글자부터 ... 처리
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/e09a23f1-6617-4af7-bed0-54f5f1c28cae" width=130px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/d7a22607-17a8-49b3-bd3e-ce92b65151d8" width=130px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/1336b19c-94e6-4f5c-b656-8c1e69b6b4c4" width=130px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/9ab48e82-b386-4ee0-81e9-a483c70c8f50" width=130px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/b60c45df-a6c7-4777-b1f3-71d97bf83be2" width=130px />|
|:---:|:---:|:---:|:---:|:---:| …
> [FEAT] 닉네임 정렬 + 글자 수 제한 구현

- fairer-iOS/fairer-iOS/Screens/HouseWork/EditHouseWork/ViewController/EditHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/View/SelectHouseWorkSpace/SelectHouseWorkSpaceCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/ViewController/SelectHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/ViewController/WriteHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingProfileImage/SettingProfileImageViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingProfileViewController.swift
- close #204 
[이슈1: [프로필 이미지 변경해도 수정으로 반영 안되는 문제](https://www.notion.so/1626a8a6354b4b379821d4c45c1ccd33)]
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/73ee85b1-60b8-4cdd-ad74-f6e48d7d7ef3
프로필 설정 > 프로필 이미지 변경 > 선택완료 > 입력완료 버튼까지 해야 프로필 정보를 변경할 수 있도록 로직 수정
녹화 영상처럼 프로필 설정 화면에서 입력완료 버튼을 누르지 않고 뒤로 가버리면 수정 내용이 반영되지 않습니다.
[이슈2: [nav bar 에 background Color 적용하기](https://www.notion.so/nav-bar-background-Color-4658804bd75945fa87168378b401601e)]
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/0cb8ae3a-3f2d-46c6-b196-76d45a8748f4" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/a3118821-b6c0-44d1-95a4-4f7c4b70bd16" width=200px />|
|:---:|:---:|
|<center>WriteHouseWork</center>|<center>EditHouseWork</center>|
scrollView의 top layout을 …
> [FIX] 자잘자잘한 버그 해결

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingInquiry/ViewController/SettingInquiryViewController.swift
- fairer-iOS/fairer-iOS/Screens/SettingProfileViewController.swift
- close #219 
- 문의하기 화면에서 메일을 보낸 후 모달이 내려가지 않는 버그 해결 + UX 개선을 위해 alert 추가
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/86b8b96f-a447-4045-b82e-e3def7c53a35
(디폴트 수신 계정은 fairer 계정입니다)
- 이전 화면에 나갔다 들어오면 Notification Center가 동작하지 않아 버튼이 올라오지 않는 버그 해결
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/4d6d3ede-57fc-4278-b152-9389f6c57503
- 메일 전송 성공 여부에 따라 다른 action을 처리할 수 있음
```swift
func mailComposeController(_ controller: MFMailComposeViewController, didFinishWith result: MFMailComposeResult, error: Error?) {
switch result {
case .sent, .saved, .cancelled, .failed: // 상태에 따라 분기 처리 가능
}
}
```
- 화면을 나갔다 들어왔을 때 Notification Center가 동작하지 않은 이유는 viewDidLoad에 setting 함수가 있었기 때문입니다. 한 번 로드된 이후에 실행되지 않기 때문에 당연하게.. 동작하지 않았을 겁니다 .. (머쓱) 매번 화면을 보여주기 전에 Notification을 setting 할 수 있도록 …
> [FIX] 모달 Dismiss & Notification 위치 변경

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Global/UIComponent/TextField.swift
- fairer-iOS/fairer-iOS/Screens/Setting/ChangeHouseName/ChangeHouseNameViewController.swift
- close #225 
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/2248dca3-88f4-4143-993f-f2e65ee8c993" width=150px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/d0402cd1-6243-4afc-bbf6-776cdcc644db" width=150px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/8cc914a4-7fba-41a2-9e71-e928a328781a" width=150px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/85459446-95bc-4611-a4d8-ea8cd2940f7e" width=150px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/8d62e727-e0fb-4952-b047-8d3b1893a577" width=150px />|
|:---:|:---:|:---:|:---:|:---:|
|<center>초기</center>|<center>특수문자</center>|<center>16자 초과</center>|<center>둘 다</center>|<center>올바르게 입력</center>|
- 전에는 버튼을 눌렀을 때 글자수가 초과되었고, 이모티콘을 …
> [FIX] 하우스 이름 수정 textfield 버그 해결

- fairer-iOS/fairer-iOS/Screens/HouseWork/EditHouseWork/ViewController/EditHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SelectHouseWork/ViewController/SelectHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/ViewController/WriteHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingAlarm/ViewController/SettingAlarmViewController.swift
- close #227 
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/9ca56eb6-f27a-4c02-bca0-9244a9f9bf53
공간과 세부 집안일 선택 후 다른 공간을 선택했을 때 나오는 얼럿의 확인 버튼을 누를 경우
공간과 세부 집안일이 초기화 되는데 이때 세부 집안일 목록이 hidden 처리 되어야 합니다..
지난 버그 픽스 때 인지하지 못해서 수정 후 피알 올립니당
그 김에 api 통신에서 사용하던 dump를 일부 삭제했습니당 (moya logger 가 이미 잘 프린트 해주고 있기 때문!)
> [FIX] 다른 공간 선택시 세부 집안일 목록 숨기기 

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingMain/ViewController/SettingViewController.swift
- close #232 
[회원탈퇴 구현]
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/a48c40e5-eaf4-4193-9394-109857167615
- api가 완성되지 않아서 로그아웃과 동일한 로직으로 일단 추가해두었습니다!
[GroupMain의 버그 픽스]
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/16a833ad-d110-493c-a8bf-2df5119028fe
- 뒤로 가기 버튼 삭제
- 닉네임 표시 안되는 문제 해결 (원래는 OnboardingName에서 입력한 이름을 parameter 로 전달했었음, 설정에서 넘어올 때는 OnboardingName을 거치지 않으므로 api를 연결하여 닉네임 정보를 불러옴)
- 하우스 참여 후 화면이 두 개 얹어지는 문제 해결 (push를 두 번하고 있어서 하나로 줄였어용)
GroupMain에서 앱을 나간 후 다시 들어오면 SceneDelegate 에서 login 뷰컨으로 navigate 하는 문제가 발견되었습니다~ 이와 관련해서는 규철님이 해결하고 계시니까 테스트 할 때 GroupMain에서 다시 빌드하거나.. 앱을 나가지 마시길 참고 부탁드립니다 ~
> [ADD] 회원탈퇴 구현 + 관련 버그 수정

- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Global/Util/RootHandler.swift
- fairer-iOS/fairer-iOS/Global/Util/UserDefaultHandler.swift
- fairer-iOS/fairer-iOS/Network/API/OauthAPI.swift
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseMakeName/HouseMakeNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/ManageHouse/ManageHouseViewController.swift
- close #233 
- 팀 참가하지 않은 유저를 분기처리를 scene과 로그인vc에서 진행해봤습니다.
- 기존에는 로그인 여부만 확인했지만, 회원가입 이후 팀을 나갔거나, 온보딩에서 팀을 설정할 때 앱이 종료된 경우를 미리 확인하지 못했습니다.
- 그래서 총 3가지 유저로 분기를 생각해봤습니다.
[로그인 시]
1. 신규유저가 아니면서, 팀에 참가한 유저 -> 흠으로
2. 신규유저가 아니면서, 팀에 참가하지 않은 유저 -> 그룹 메인으로 (팀을 나갔거나, 온보딩 팀 설정 중 앱을 종료)
3. 신규유저면서, 팀에 참가하지 않은 유저 -> 온보딩 뷰로 (사실 신규유저가 팀에 참가했는지 안했는지 확인할 필요가 없지만.. 혹시 몰라서 설정해두었습니다.)
[앱 접속 시]
1. 로그인한 유저면서, 팀에 참가한 유저 -> 홈으로
2. 로그인한 유저면서, 팀에 참가하지 않은 유저 -> 그룹메인으로
3. 로그인하지 않은 유저 -> 로그인뷰로 **(로그인뷰로 이동 후 로그인 시 한번 더 hasTeam을 확인합니다.)**
- 테스트가 많이 필요할 거 같습니다..
> [FIX] 팀 참가하지 않은 유저 분기처리

- fairer-iOS/fairer-iOS/Global/Extension/UIImageView+Extension.swift
- close #242 
안드로이드와 iOS 기기에서 저장한 이미지 주소가 달라 이미지 캐싱 과정에서 런타임 에러가 발생했습니다.
그동안은 iOS 기기들로만 테스트를 해왔기 때문에 발견하지 못한 문제인데요.
안드 기기와 함께 사용하는 앱이기 때문에 앱 심사를 올리기 전에 급하게 수정했습니다.
안드 이미지 주소는 
`2Forange1-3x.png?`
iOS 이미지 주소는
`2Fic_profile3.svg?`
와 같은 형식으로 구성되어 있습니다.
공통적으로 가지고 있는 문자열인, **2F**를 기준으로 뒷 부분만 잘라낸 후
.svg가 있으면 .svg기준으로 (orange1 등 이미지 색으로 네이밍 된 경우)
-3x가 있으면 -3x 기준으로 (profile1 등 숫자를 기준으로 네이밍 된 경우)
앞 부분을 추출합니다.
위에서 찾아본 조건에 해당되는 이미지 주소가 없다면,
default 이미지로 지정되도록 하였습니다.
이로써 이미지 캐싱과 로드 과정에서 런타임 에러가 발생하여 앱이 폭발하는 일은 없습니다!
백엔드 분에게 이미지 주소가 변경될 가능성이 있냐고 여쭤봤을 때 없다고 해주셨지만,
추후 이미지 주소가 변경된다면 위와 같은 문제가 발생할 가능성은 충분히 있습니당..
이미지 주소로 프로필 이미지를 판별하는 건, 서버에 의존적이라서 이 문제에 대해 다시 고민해보는 게 좋을 것 같습니다.
> [FIX] 이미지 파싱 로직 수정

- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/ViewController/HouseInviteCodeViewController.swift
- close #247 
- 버튼 설정 메서드가 viewWillAppear와 viewDidLoad에 두번 설정되어 있었습니다.
> [FIX] 건너뛰기 할 경우 Home 화면이 두 번 navigate 되는 이슈

- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Network/API/TeamsAPI.swift
- fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
- close #246 
잘못된 초대코드를 입력할 경우 toast가 뜨며 화면이 넘어가지 않습니다.
```swift
case .requestErr(let error):
guard let errorResponse = error as? UserErrorResponse else { return }
self?.showToast(errorResponse.errorMessage)
```
기존에 작성된 코드는 언뜻 보기에는 문제가 없어 보입니다.
하지만 실제로 400 error가 뜨면 result 자체가 들어오지 않아 case 문에서 분기가 처리되지 않습니다.
TeamsAPI의 function에서 먼저 failure가 잡히는데 이때 success 결과만 EnterHouseVC에 넘어오기 때문인데요.
TeamsAPI에서 failure 결과에 대한 completion handler 를 추가하여 VC에 넘겨주었더니 잘 동작합니다.
원래 작성해주신대로 error 결과 구조체의 errorMessage를 toast 문구로 사용하려고 했으나 
completion handler 로 전달되는 request error result값은 기존과는 다른 형태라서
TextLiteral에 메시지를 직접 작성해서 추가해두었습니다!
> [FIX] 잘못된 초대코드 입력 핸들링

- fairer-iOS/fairer-iOS.xcodeproj/project.pbxproj
- fairer-iOS/fairer-iOS/Global/Literal/TextLiteral.swift
- fairer-iOS/fairer-iOS/Screens/Auth/Login/LoginViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/View/InviteCodeButtonView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/HomeView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/ToolBar/HomeViewControllerToolBar.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionView.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/View/WeekCalendarView/HomeWeekCalendarCollectionViewCell.swift
- fairer-iOS/fairer-iOS/Screens/Home/SettingHomeRule/ViewController/View/SettingHomeRuleHeaderView.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingMain/ViewController/SettingViewController.swift
release를 준비하는 과정, 그리고 리젝 사유를 해결하는 과정에서 바뀐 코드들이 많아서
아래에 자세하게 설명을 추가해두었습니다.
궁금한 사항 있으시다면 언제든지 댓글 남겨주시고,
저 나름대로 꼼꼼하게 검수하면서 반영했으나
develop과 main에 머지될 사항이니 꼼꼼하게 확인 부탁드립니다.
[1] Build version 변경: 2 -> 7
[2] 사용자 이름 입력 라이팅 변경: 이름 > 닉네임
[3] 로그인 후 화면이 넘어가지 않는 이슈 해결 (LoginVC)
[4] 카카오톡 공유하기 버튼 임시로 hidden 처리
[5] 집안일 추가하기 버튼 height 줄이기: 인디케이터가 없는 버젼을 가지고 있는 기기의 경우 (일부 아이폰과 아이패드) 집안일 추가하기 버튼의 backgroundView가 너무 커서 필요 이상의 영역을 차지하여 height를 줄였습니다.
height를 줄인 후 기존에 그림자 역할을 하던 뷰 역시 작아져서 safe area를 기준으로 선이 생겼었는데요. 그걸 해결하기 위해 집안일 버튼 추가하기 영역의 상단에 view를 추가하여 윗부분에만 그림자가 있는 것처럼 처리하였습니다.
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/a0959a1a-ac6e-4a64-9e5e-6a15050b45f8" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/e6ca1fd9-93ed-4189-9944-8f94d86aedd2" …
> [CHORE] v1.0.0 (build 7) 릴리즈에 따른 develop 브랜치 업데이트

- fairer-iOS/fairer-iOS/Screens/Group/GroupMain/GroupMainViewController.swift
- fairer-iOS/fairer-iOS/Screens/Home/Home/ViewController/HomeViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/EditHouseWork/ViewController/EditHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/SetHouseWork/ViewController/SetHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/HouseWork/WriteHouseWork/ViewController/WriteHouseWorkViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/ChangeHouseName/ChangeHouseNameViewController.swift
- fairer-iOS/fairer-iOS/Screens/Setting/SettingAlarm/ViewController/SettingAlarmViewController.swift
- close #253 
[api 호출 시점 변경: viewDidLoad > viewWillAppear]
- ChangeHouseNameVC, SettingAlarmVC, EditHouseWorkVC, SetHouseWorkVC, WriteHouseWorkVC, GroupMainVC
**개선 전**
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/9aa1c6f7-47a5-4af6-9d74-8f9358dd71ad
**개선 후**
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/72c5e121-556f-42a6-9c34-84d368e7587f
[HomeVC 코드 정리]
api 호출이 가장 많아서 로드가 느렸던 HomeVC의 코드 일부를 정리했습니다.
주간 캘린더의 특정 날짜를 터치한 후 바로 다른 날짜를 터치하면 로딩이 길어져서 날짜 셀이 selected 되지 않는 문제가 있었는데요.
주간 캘린더의 날짜 셀을 눌렀을 때 (선택한 날짜 집안일 정보 + 해당 주 집안일 정보)를 불러와서 딜레이가 있었던 겁니다!
셀을 눌렀을 때 매번 해당 주에 대한 집안일 정보를 불러오기보다는 주 정보가 업데이트 되어야 하는 시기에만 호출되도록 수정했습니다.
그래서 주간 집안일 정보는 
1) 다른 화면에 다녀왔을 때  
2) 지난주 혹은 다음주로 스와이프할 때 
3) datepicker로 날짜 변경했을 때
만 불러옵니다!
**개선 전** …
> [CHORE] api/data binding 속도 개선하기

- fairer-iOS/fairer-iOS/Global/Supports/Info.plist
- fairer-iOS/fairer-iOS/Global/Supports/SceneDelegate.swift
- fairer-iOS/fairer-iOS/Screens/Auth/OnboardingProfile/ViewController/OnboardingProfileViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/AlreadyInGroup/AlreadyInGroupViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/EnterHouse/EnterHouseViewController.swift
- fairer-iOS/fairer-iOS/Screens/Group/HouseInviteCode/View/InviteCodeButtonView.swift
- close #256 
|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/14d1d1c4-5362-4a06-804e-443ac37bb4ff" width=200px />|<img src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/183b10b8-31ae-46af-a535-4ae580ba274f" width=200px />|
|:---:|:---:|
카카오톡으로 초대카드를 공유하는 프로세스는 준혁님(천재 막둥이)께서 구현해주셨는데요.
저는 유저가 카카오톡에서 초대 받기를 눌렀을 때 이후의 프로세스를 구현했습니다.
먼저 초대를 받은 유저는 크게 3 가지 상태 중 하나에 놓여 있을 겁니다.
이 같은 경우에는 페어러를 다운 받을 수 있도록 앱스토어 모달을 띄웠습니다.
준혁님께서 구현하실 시기에는 앱이 출시가 안돼서 kakao developers에서 web link를 넣으셨는데,
안드에서도 동일하게 web link를 사용하고 있어서 플레이 스토어로 넘어가는 이슈가 있었죠..
이 이슈는 앱이 출시됨에 따라 해결됐습니다. 
앱스토어 ID (Apple ID)를 넣으면 자동으로 앱스토어로 링크 됩니다!
https://github.com/fairer-iOS/fairer-iOS/assets/81340603/8e7b4684-5a06-4ed5-aaec-2a5668d2306b
hasTeam을 검사해서 팀이 있는 경우 AlreadyInGroupVC로 이동합니다! …
> [FEAT] 카카오톡 공유하기 구현
